app/blueprints/asns.py
from flask import Blueprint
from flask import render_template, flash, redirect, url_for, request, g  # noqa
from flask.ext.login import current_user, login_required
from datetime import datetime
from app.forms import *
from app.models import *

asns = Blueprint('asns', __name__, template_folder='templates')

@asns.route('/asn/new', methods=['GET', 'POST'])
@login_required
def create():
    form = FormAS()
    form.communities.query = current_user.get_communities()
    form.contacts.query = current_user.get_contacts()
    form.submit.label.text='Create ASN'
    if form.validate_on_submit():
        asn = AS()
        form.populate_obj(asn)
        asn.created = datetime.now()
        asn.changed = datetime.now()
        db.session.add(asn)
        db.session.commit()
        flash('Customer Edge has been created')
        return redirect(url_for('asns.list'))
    return render_template("as/detail.html", form=form, edit=False)


@asns.route('/asn/delete/<asn_id>')
@login_required
def delete(asn_id):
    asn=AS.query.filter_by(id=asn_id)
    asn.delete()
    db.session.commit()
    flash('AS deleted successfully!')
    return redirect(url_for('asns.list'))


@asns.route('/asn/<asn_id>', methods=['GET', 'POST'])
@login_required
def edit(asn_id):
    comm_subq = Community.query.filter(
        Community.contacts.contains(current_user)).subquery()
    this_asn = AS.query.filter_by(id=asn_id).join(comm_subq, AS.Community).first()
    if this_asn is None:
        flash('Access denied!')
        return redirect(url_for('index'))
    form = FormAS(obj=this_asn, edit=True)
    form.communities.query = current_user.get_communities()
    form.contacts.query = current_user.get_contacts()
    form.submit.label.text='Update ASN'
    if form.validate_on_submit():
        form.populate_obj(this_asn)
        this_asn.changed = datetime.now()
        db.session.add(this_asn)
        db.session.commit()
        return redirect(url_for('asns.list'))
    return render_template("as/detail.html", form=form, edit=True)


@asns.route('/asn')
@asns.route('/asn/')
@login_required
def list():
    return render_template("as/list.html",asns=current_user.get_asns())

app/templates/as/detail.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
    {% if form.data.edit %}
        Backbone Admin Tool - Edit AS
    {% else %}
        Backbone Admin Tool - Create AS
    {% endif %}
{% endblock %}
{% block page_content %}
    <div class="page-header">
    {% if form.data.edit %}
        <h1>Edit Autonomous System</h1>
    {% else %}
        <h1>Create Autonomous System</h1>
    {% endif %}
    </div>
    <div class="col-md-4">
        {{ wtf.quick_form(form) }}
    </div>
{% endblock %}

app/templates/as/list.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Backbone Admin Tool - ASNs{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Your Communitiy ASNs</h1>
</div>
<div class="col-md-18">
	<h3>AS List</h3>
	<table class="table table-striped">
        <colgroup>
            <col class="col-md-1">
	        <col class="col-md-2">
	        <col class="col-md-2">
	        <col class="col-md-1">
	        <col class="col-md-2">
	        <col class="col-md-2">
	        <col class="col-md-2">
	    </colgroup>
	<tr>
		<th>ASN</th>
		<th>AS-Name</th>
		<th>Description</th>
		<th>Approved</th>
		<th>Contacts</th>
		<th>Community</th>
        <th>Actions</th>
	</tr>
	{% for asn in asns %}
	<tr>
        <td> {{ asn.asn }} </td>
	    <td> {{ asn.name }} </td>
		<td> {{ asn.descr }} </td>
        <td>
            {% if asn.isapproved() %}
				<span class="glyphicon glyphicon-ok-circle"></span>
			{% else %}
				<span class="glyphicon glyphicon-ban-circle"></span>
            {% endif %}
        </td>
        <td>
			<ul class="list-group">
			{% for contact in asn.contacts %}
				<li class="list-group-item">{{ contact.nickname }}</li>
			{% endfor %}
			</ul>
		</td>
		<td> 
			<ul class="list-group">
			{% for community in asn.Community %}
				<li class="list-group-item">{{ community.name }}</li>
			{% endfor %}
			</ul>
		</td>
		<td><a class="btn btn-primary btn-sm active" href="{{ url_for('asns.edit', asn_id=asn.id) }}">Edit</a>&nbsp;<a href="{{ url_for('asns.delete', asn_id=asn.id) }}" class="btn btn-danger btn-sm active">Delete</a></td>
	</tr>
	{% endfor %}
	</table></br></br>
	<a class="btn btn-primary btn-sm active" href="{{ url_for('asns.create') }}">Create New ASN</a>
</div>
{% endblock %}