app/blueprints/customeredges.py
from flask import Blueprint
from flask import render_template, flash, redirect, url_for, request, g  # noqa
from flask.ext.login import current_user, login_required
from datetime import datetime
from app.forms import *
from app.models import *
from netaddr import *

customeredges = Blueprint('customeredges', __name__, template_folder='templates')

@customeredges.route('/customeredge/<ce_id>', methods=['GET', 'POST'])
@login_required
def edit(ce_id):
    if current_user.is_ce_permitted(ce_id) is False:
        flash('You don''t belong to the CustomerEdge''s Community')  # noqa
        return redirect(url_for('customeredges.list'))
    ce = CustomerEdge.query.filter_by(id=ce_id).options(
        db.joinedload('asn')).options(db.lazyload('community')).first()
    sessions = PeeringSession.query.filter_by(ce_id=ce.id).options(
        db.joinedload('TunnelType')).options(db.joinedload('ProviderEdge'))
    form = CustomerEdgeForm(obj=ce, edit=True)
    form.asn.query = current_user.get_asns()
    form.community.query = current_user.get_communities()
    form.submit.label.text = 'Update Customer Edge'
    sessionform = SessionForm()
    sessionform.type.query = TunnelType.query
    if form.validate_on_submit():
        flash('CustomerEdge edited successfully!')
        return redirect(url_for('customeredges.list'))
    if sessionform.validate_on_submit():
        print('gen sessions')
        #Generate GRE tunnels, ips and sessions
        pes = ProviderEdge.query.all()
        for pe in pes:
            transfer = Prefix.get_availprefix(1,4,31)
            session = PeeringSession()
            session.pe_id = pe.id
            session.ce_id = ce_id
            session.pe_v4 = str(transfer[0])
            session.ce_v4 = str(transfer[1])
            session.tunneltype_id = 1
            session.enabled = 1
            db.session.add(session)
            db.session.commit()
        return redirect(url_for('customeredges.edit',ce_id=ce_id))
    return render_template(
        'customeredge/detail.html',
        ce=ce,
        sessions=sessions, form=form, sessionform=sessionform)

@customeredges.route('/customeredge/<ce_id>/<session_id>/<state>')
@login_required
def session_changestate(ce_id, session_id, state):
    if current_user.is_ce_permitted(ce_id) is False:
        flash('You don''t belong to the CustomerEdge''s Community')  # noqa
        return redirect(url_for('customeredges.list'))
    session = PeeringSession.query.filter_by(id=session_id).first()
    session.enabled = state
    db.session.add(session)
    db.session.commit()
    return redirect(url_for('customeredges.edit',ce_id=ce_id))

@customeredges.route('/customeredge/<ce_id>/deletesessions')
@login_required
def delete_sessions(ce_id):
    if current_user.is_ce_permitted(ce_id) is False:
        flash('You don''t belong to the CustomerEdge''s Community')  # noqa
        return redirect(url_for('customeredges.list'))
    ce = CustomerEdge.query.filter_by(id=ce_id).first()
    ce.sessions.delete()
    db.session.commit()
    return redirect(url_for('customeredges.edit', ce_id=ce_id))

@customeredges.route('/customeredge')
@login_required
def list():
    ces = current_user.get_customeredges()
    return render_template('customeredge/list.html',
                           customeredges=ces)

@customeredges.route('/customeredge/delete/<ce_id>')
@login_required
def delete(ce_id):
    this_edge=CustomerEdge.query.filter_by(id=ce_id)
    this_edge.delete()
    db.session.commit()
    flash('CustomerEdge has been deleted successfully')
    return redirect(url_for('customeredges.list'))

@customeredges.route('/customeredge/create', methods=['GET', 'POST'])
@login_required
def create():
    form = CustomerEdgeForm()
    form.community.query = current_user.get_communities()
    form.asn.query = current_user.get_asns()
    form.submit.label.text='Create CustomerEdge'
    if form.validate_on_submit():
        ce = CustomerEdge()
        form.populate_obj(ce)
        db.session.add(ce)
        db.session.commit()
        flash('Customer Edge has been created')
        return redirect(url_for('customeredges.list'))
    return render_template("customeredge/new.html", form=form)

app/templates/customeredge/detail.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Backbone Admin Tool - CEs{% endblock %}

{% block page_content %}
    <div class="page-header">
        <h1>Customer Edge - {{ ce.name }} </h1>
    </div>
    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
        !function ($) {
            $(function () {
                window.prettyPrint && prettyPrint()
            })
        }(window.jQuery)
    </script>
    <div class="col-md-7">
        {% if form.errors %}
            <ul class="errors">
                {% for field_name, field_errors in form.errors|dictsort if field_errors %}
                    {% for error in field_errors %}
                        <li>{{ form[field_name].label }}: {{ error }}</li>
                    {% endfor %}
                {% endfor %}
            </ul>
        {% endif %}
        {% if sessionform.errors %}
            <ul class="errors">
                {% for field_name, field_errors in sessionform.errors|dictsort if field_errors %}
                    {% for error in field_errors %}
                        <li>{{ sessionform[field_name].label }}: {{ error }}</li>
                    {% endfor %}
                {% endfor %}
            </ul>
        {% endif %}
    </div>
    <form class="form-horizontal" role="form" method="post">
        {{ form.csrf_token() }}
        <div class="container">
            <h3>Basic Information</h3>
            <p>Find Basic Information below:</p>
            <div class="form-group">
                <label class="control-label col-sm-2" for="pwd">Name</label>
                <div class="col-sm-10">{{ form.name(class="form-control") }}</div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="pwd">FQDN</label>
                <div class="col-sm-10">{{ form.fqdn(class="form-control") }}</div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="pwd">AS</label>
                <div class="col-sm-10">{{ form.asn(class="form-control") }}</div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="pwd">IPv4</label>
                <div class="col-sm-10">{{ form.ipv4(class="form-control") }}</div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="pwd">IPv6</label>
                <div class="col-sm-10">{{ form.ipv6(class="form-control") }}</div>
            </div>
        </div>
        <div class="container">
            <h3>Communities</h3>
            <p>This CustomerEdge is visible to following Community:</p>
            <div class="form-group">
                <label class="control-label col-sm-2">Community</label>
                <div class="col-sm-10">{{ form.community(class="form-control") }}</div>
            </div>
            <div class="form-group">
                <div class="col-sm-5">{{ form.submit(class="form-control btn btn-primary") }}</div>
    </form></div></div>
    <form class="form-horizontal" role="sessionform" method="post">
        {{ sessionform.csrf_token() }}
        <div class="container">
            <h3>Customer Edge Sessions</h3>
            {% if ce.sessions.count() == 0 %}
                <p>There are no sessions setup for your community.</p>
                <div class="form-group">
                    <label class="control-label col-sm-2" for="pwd">Tunnel Type</label>
                    <div class="col-sm-10">{{ sessionform.type(class="form-control") }}</div>
                </div>
                <div class="form-group">
                    <div class="col-sm-5">{{ sessionform.submit(class="form-control btn btn-primary") }}</div>
                </div>
            {% else %}

                <p>Following Sessionss are setup to your CE:</p>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>ProviderEdge</th>
                        <th>PEv4</th>
                        <th>PEv6</th>
                        <th>CEv4</th>
                        <th>CEv6</th>
                        <th>Type</th>
                        <th>Enabled</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for session in ce.sessions %}
                        <tr>
                            <td>{{ session.ProviderEdge.name }}
                                ({{ session.ProviderEdge.ipv4 }}, {{ session.ProviderEdge.ipv6 }})
                            </td>
                            <td>{{ session.pe_v4 }}</td>
                            <td>{{ session.pe_v6 }}</td>
                            <td>{{ session.ce_v4 }}</td>
                            <td>{{ session.ce_v6 }}</td>
                            <td>{{ session.TunnelType.name }}</td>
                            {% if session.enabled %}
                                <td><span class="glyphicon glyphicon-ok-circle"></span></td>
                                <td><a href="{{ url_for('customeredges.session_changestate', ce_id=ce.id,session_id=session.id, state=0) }}" class="btn btn-warning">Disable</a></td>
                            {% else %}
                                <td><span class="glyphicon glyphicon-ban-circle"></span></td>
                                <td><a href="{{ url_for('customeredges.session_changestate', ce_id=ce.id,session_id=session.id, state=1) }}" class="btn btn-success">Enable</a></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div class="form-group">
                    <div class="col-sm-5">
                        <a href="{{ url_for('customeredges.delete_sessions', ce_id=ce.id) }}" class="btn btn-danger">Delete Sessions</a>
                    </div>
                </div>
            {% endif %}
    </form></div>

    {% if ce.sessions.count() > 0 %}
        <div class="col-md-6">
            <div class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" href="#collapse1">Configuration for /etc/network/interfaces</a>
                        </h4>
                    </div>
                    <div id="collapse1" class="panel-collapse collapse" style="padding: 5px;">
        <pre class="prettyprint" style="margin-bottom: 0px;">
{% for session in ce.sessions %}
    <span class="nt">auto</span> tun-{{ session.ProviderEdge.name }}
    interface tun-{{ session.ProviderEdge.name }} inet tunnel
    mode gre
    ttl 64
    mtu 1400
    netmask 255.255.255.255
    address {{ session.ce_v4 }}
    dstaddr {{ session.pe_v4 }}
    endpoint {{ session.ProviderEdge.ipv4 }}
    local {{ session.CustomerEdge.ipv4 }}

    inteface tun-{{ session.ProviderEdge.name }} inet6 static
    address {{ session.ce_v6 }}/64
{% endfor %}
</pre>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" href="#collapse2">Configuration for netctl</a>
                        </h4>
                    </div>
                    <div id="collapse2" class="panel-collapse collapse" style="padding: 5px;">
        <pre class="prettyprint" style="margin-bottom: 0px;">
{% for session in ce.sessions %}
    <span class="nt">auto</span> tun-{{ session.ProviderEdge.name }}
    interface tun-{{ session.ProviderEdge.name }} inet tunnel
    mode gre
    ttl 64
    mtu 1400
    netmask 255.255.255.255
    address {{ session.ce_v4 }}
    dstaddr {{ session.pe_v4 }}
    endpoint {{ session.ProviderEdge.ipv4 }}
    local {{ session.CustomerEdge.ipv4 }}

    inteface tun-{{ session.ProviderEdge.name }} inet6 static
    address {{ session.ce_v6 }}/64
{% endfor %}
        </pre>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

app/templates/customeredge/list.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Backbone Admin Tool - CEs{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Your Communities Customer Edges</h1>
</div>
<div class="col-md-16">
	<table class="table table-striped">
        <colgroup>
            <col class="col-md-1">
	    <col class="col-md-1">
	    <col class="col-md-1">
	    <col class="col-md-1">
	    <col class="col-md-1">
	    <col class="col-md-1">
	    <col class="col-md-1">
	</colgroup>
	<tr>
		<th>Name</th>
		<th>FQDN</th>
		<th>IPv4</th>
		<th>IPv6</th>
		<th>ASN</th>
		<th>Community</th>
		<th>Actions</th>
	</tr>
	{% for ce in customeredges %}
	<tr>
        	<td> {{ ce.name }} </td>
	        <td> {{ ce.fqdn }} </td>
		<td> {{ ce.ipv4 }} </td>
		<td> {{ ce.ipv6 }} </td>
		<td> {{ ce.asn.asn }} </td>
		<td> {{ ce.community }}</td>
		<td><a class="btn btn-primary btn-sm active" href="{{ url_for('customeredges.edit', ce_id=ce.id) }}">Edit</a>&nbsp;<a href="{{ url_for('customeredges.delete', ce_id=ce.id) }}" class="btn btn-danger btn-sm active">Delete</a></td>

	</tr>
	{% endfor %}
	<table></br></br>
	<a class="btn btn-primary btn-sm active" href="{{ url_for('customeredges.create') }}">Create New Customer Edge</a>
</div>
{% endblock %}

app/templates/customeredge/new.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Backbone Admin Tool - Create Customer Edge{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Create Customer Edge</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}