app/blueprints/contacts.py
from flask import Blueprint
from flask import render_template, flash, redirect, url_for, request, g  # noqa
from flask.ext.login import current_user, login_required
from app.forms import *
from app.models import *

contacts = Blueprint('contacts', __name__, template_folder='templates')


@contacts.route('/contact')
@contacts.route('/contact/')
@login_required
def list():
    return render_template('contact/list.html',
                           contacts=current_user.get_contacts(),
                           admin=current_user.admin)

@contacts.route('/contacts/delete/<contact_id>')
@login_required
def delete(contact_id):
    contact=Contact.query.filter_by(id=contact_id)
    contact.delete()
    db.session.commit()
    flash('Contact deleted successfully!')
    return redirect(url_for('contacts.list'))

@contacts.route('/contact/new', methods=['GET', 'POST'])
@login_required
def create():
    form = FormContact()
    form.communities.query = current_user.get_communities()
    if form.validate_on_submit():
        contact = Contact()
        form.populate_obj(contact)
        contact.set_password(form.newpassword.data)
        db.session.add(contact)
        db.session.commit()
        flash('Contact has been created')
        return redirect(url_for('contacts.list'))
    return render_template("contact/detail.html", form=form)


@contacts.route('/contact/<contact_id>', methods=['GET', 'POST'])
@login_required
def edit(contact_id):
    contact = Contact.query.filter_by(id=contact_id).first_or_404()
    communities_self = Community.query.join(
        Contact,
        Community.contacts
    ).filter_by(id=current_user.id)
    communities_edit = Community.query.join(
        Contact,
        Community.contacts
    ).filter_by(id=contact_id)
    same = False
    for community_self in communities_self:
        for community_edit in communities_edit:
            if community_edit.id == community_self.id:
                community_self.selected = True
                same = True
    if (current_user.admin is False and int(contact_id) != current_user.id) or (
                    current_user.admin is True and same is False):  # noqa
        flash('You don''t have permissions to edit selected contact information')  # noqa
        return redirect(url_for('index'))
    form = FormContact(obj=contact, edit=True)
    form.communities.query = current_user.get_communities()
    if form.validate_on_submit():
        form.populate_obj(contact)
        if form.newpassword is not None:
            contact.set_password(form.newpassword.data)
        db.session.add(contact)
        db.session.commit()
        return redirect(url_for('contacts.list'))
    return render_template('contact/detail.html',
                           contact=contact,
                           communities=communities_self,
                           form=form)

app/blueprints/customeredges.py
from flask import Blueprint
from flask import render_template, flash, redirect, url_for, request, g  # noqa
from flask.ext.login import current_user, login_required
from datetime import datetime
from app.forms import *
from app.models import *
from netaddr import *

customeredges = Blueprint('customeredges', __name__, template_folder='templates')

@customeredges.route('/customeredge/<ce_id>', methods=['GET', 'POST'])
@login_required
def edit(ce_id):
    if current_user.is_ce_permitted(ce_id) is False:
        flash('You don''t belong to the CustomerEdge''s Community')  # noqa
        return redirect(url_for('customeredges.list'))
    ce = CustomerEdge.query.filter_by(id=ce_id).options(
        db.joinedload('asn')).options(db.lazyload('community')).first()
    sessions = PeeringSession.query.filter_by(ce_id=ce.id).options(
        db.joinedload('TunnelType')).options(db.joinedload('ProviderEdge'))
    form = CustomerEdgeForm(obj=ce, edit=True)
    form.asn.query = current_user.get_asns()
    form.community.query = current_user.get_communities()
    form.submit.label.text = 'Update Customer Edge'
    sessionform = SessionForm()
    sessionform.type.query = TunnelType.query
    if form.validate_on_submit():
        flash('CustomerEdge edited successfully!')
        return redirect(url_for('customeredges.list'))
    if sessionform.validate_on_submit():
        print('gen sessions')
        #Generate GRE tunnels, ips and sessions
        pes = ProviderEdge.query.all()
        for pe in pes:
            transfer = Prefix.get_availprefix(1,4,31)
            session = PeeringSession()
            session.pe_id = pe.id
            session.ce_id = ce_id
            session.pe_v4 = str(transfer[0])
            session.ce_v4 = str(transfer[1])
            session.tunneltype_id = 1
            session.enabled = 1
            db.session.add(session)
            db.session.commit()
        return redirect(url_for('customeredges.edit',ce_id=ce_id))
    return render_template(
        'customeredge/detail.html',
        ce=ce,
        sessions=sessions, form=form, sessionform=sessionform)

@customeredges.route('/customeredge/<ce_id>/<session_id>/<state>')
@login_required
def session_changestate(ce_id, session_id, state):
    if current_user.is_ce_permitted(ce_id) is False:
        flash('You don''t belong to the CustomerEdge''s Community')  # noqa
        return redirect(url_for('customeredges.list'))
    session = PeeringSession.query.filter_by(id=session_id).first()
    session.enabled = state
    db.session.add(session)
    db.session.commit()
    return redirect(url_for('customeredges.edit',ce_id=ce_id))

@customeredges.route('/customeredge/<ce_id>/deletesessions')
@login_required
def delete_sessions(ce_id):
    if current_user.is_ce_permitted(ce_id) is False:
        flash('You don''t belong to the CustomerEdge''s Community')  # noqa
        return redirect(url_for('customeredges.list'))
    ce = CustomerEdge.query.filter_by(id=ce_id).first()
    ce.sessions.delete()
    db.session.commit()
    return redirect(url_for('customeredges.edit', ce_id=ce_id))

@customeredges.route('/customeredge')
@login_required
def list():
    ces = current_user.get_customeredges()
    return render_template('customeredge/list.html',
                           customeredges=ces)

@customeredges.route('/customeredge/delete/<ce_id>')
@login_required
def delete(ce_id):
    this_edge=CustomerEdge.query.filter_by(id=ce_id)
    this_edge.delete()
    db.session.commit()
    flash('CustomerEdge has been deleted successfully')
    return redirect(url_for('customeredges.list'))

@customeredges.route('/customeredge/create', methods=['GET', 'POST'])
@login_required
def create():
    form = CustomerEdgeForm()
    form.community.query = current_user.get_communities()
    form.asn.query = current_user.get_asns()
    form.submit.label.text='Create CustomerEdge'
    if form.validate_on_submit():
        ce = CustomerEdge()
        form.populate_obj(ce)
        db.session.add(ce)
        db.session.commit()
        flash('Customer Edge has been created')
        return redirect(url_for('customeredges.list'))
    return render_template("customeredge/new.html", form=form)

app/blueprints/prefixes.py
from flask import Blueprint
from flask import render_template, flash, redirect, url_for, request, g  # noqa
from flask.ext.login import current_user, login_required
from datetime import datetime
from app.forms import *
from app.models import *

prefixes = Blueprint('prefixes', __name__, template_folder='templates')

@prefixes.route('/prefix')
@login_required
def list():
    community = Community.query.join(
        Contact,
        Community.contacts
    ).filter_by(id=current_user.id).first_or_404()
    prefixes = Prefix.query.filter_by(
        community_id=community.id
    ).options(
        db.joinedload('nameservers')
    ).options(
        db.joinedload('contacts')
    ).options(
        db.subqueryload('PrefixType')
    ).options(db.subqueryload('Site'))
    if prefixes.count() == 0:
        flash('No prefixes are currently assigned to you.')  # noqa
        return redirect(url_for('index'))
    return render_template('prefix/list.html',
                           prefixes=prefixes)


@prefixes.route('/prefix/<prefix_id>')
@login_required
def edit(prefix_id):
    prefix = Prefix.query.filter_by(id=prefix_id).options(
        db.subqueryload('nameservers')
    ).options(
        db.subqueryload('contacts')
    ).options(
        db.subqueryload('PrefixType')
    ).options(
        db.subqueryload('Site')
    ).options(
        db.subqueryload('Community')
    ).first_or_404()
    community = Community.query.filter_by(id=prefix.community_id).join(
        Contact,
        Community.contacts
    ).filter_by(id=current_user.id)
    if community.count() == 0:
        flash('You don''t belong to the Prefixes Community')  # noqa
        return redirect(url_for('prefixes.list'))

    nameservers = current_user.get_nameservers()
    return render_template(
        'prefix/detail.html',
        prefix=prefix,
        nameservers=nameservers)

app/templates/backbone/as-create.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Backbone Admin Tool - Create AS{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Create AS</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/backbone/as.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
    {% if form.data.edit %}
        Backbone Admin Tool - Edit AS
    {% else %}
        Backbone Admin Tool - Create AS
    {% endif %}
{% endblock %}
{% block page_content %}
    <div class="page-header">
    {% if form.data.edit %}
        <h1>Edit Autonomous System</h1>
    {% else %}
        <h1>Create Autonomous System</h1>
    {% endif %}
    </div>
    <div class="col-md-4">
        {{ wtf.quick_form(form) }}
    </div>
{% endblock %}

app/templates/backbone/customeredge-create.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Backbone Admin Tool - Create Customer Edge{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Create Customer Edge</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/backbone/customeredge.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Backbone Admin Tool - CEs{% endblock %}

{% block page_content %}
<div class="page-header">
	<h1>Customer Edge - {{ ce.name }} </h1>
</div>
<div class="container">
	<h3>Basic Information</h3>
	<p>Find Basic Information below:</p>
	FQDN: {{ ce.fqdn }} </br>
	AS: {{ ce.AS.asn }} </br>
	IPv4: {{ ce.ipv4 }} </br>
	IPv6: {{ ce.ipv6 }} </br>
</div>
<div class="container">
	<h3>Communities</h3>
	<p>This CustomerEdge is visilble to following Communities:</p>
	<ul>
	{% for community in ce.Community %}
		<li>{{ community.name }}</li>
	{% endfor %}
	</ul>
</div>
 <div class="container">
                        <h3>Customer Edge Sessions</h3>
                        <p>Following Sessionss are setup to your CE:</p>
                        <table class="table table-striped">
                                <thead>
                                        <tr>
                                                <th>ProviderEdge</th>
                                                <th>PEv4</th>
                                                <th>PEv6</th>
                                                <th>CEv4</th>
                                                <th>CEv6</th>
						<th>Type</th>
						<th>Enabled</th>
                                                </tr>
                                </thead>
                                <tbody>
                                        {% for session in ce.sessions %}
                                        <tr>
                                                <td>{{ session.ProviderEdge.name  }}</td>
                                                <td>{{ session.pe_v4 }}</td>
                                                <td>{{ session.pe_v6 }}</td>
						<td>{{ session.ce_v4 }}</td>
						<td>{{ session.ce_v6 }}</td>
						<td>{{ session.TunnelType.name }}</td>
                                                {% if session.enabled %}
                                                <td><span class="glyphicon glyphicon-ok-circle"></span></td>
                                                {% else %}
                                                <td><span class="glyphicon glyphicon-ban-circle"></span></td>
                                                {% endif %}
                                                <td>&nbsp;</td>
                                        </tr>
                                        {% endfor %}
                                </tbody>
                        </table>
                </div>

{% endblock %}

app/templates/backbone/customeredges.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Backbone Admin Tool - CEs{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Your Communities Customer Edges</h1>
</div>
<div class="col-md-16">
	<table class="table table-striped">
        <colgroup>
            <col class="col-md-1">
	    <col class="col-md-1">
	    <col class="col-md-1">
	    <col class="col-md-1">
	    <col class="col-md-1">
	    <col class="col-md-1">
	    <col class="col-md-1">
	</colgroup>
	<tr>
		<th>Name</th>
		<th>FQDN</th>
		<th>IPv4</th>
		<th>IPv6</th>
		<th>ASN</th>
		<th>Community</th>
		<th>Actions</th>
	</tr>
	{% for ce in customeredges %}
	<tr>
        	<td> {{ ce.name }} </td>
	        <td> {{ ce.fqdn }} </td>
		<td> {{ ce.ipv4 }} </td>
		<td> {{ ce.ipv6 }} </td>
		<td> {{ ce.AS.asn }} </td>
		<td>
			<ul>
			{% for community in ce.Community %}
				<li>{{ community.name }}</li>
		        {% endfor %}
			</ul>
		</td>
		<td><a class="btn btn-primary btn-sm active" href="{{ url_for('customeredges.edit', ce_id=ce.id) }}">Edit</a>&nbsp;<a href="{{ url_for('customeredges.delete', ce_id=ce.id) }}" class="btn btn-danger btn-sm active">Delete</a></td>

	</tr>
	{% endfor %}
	<table></br></br>
	<a class="btn btn-primary btn-sm active" href="{{ url_for('customeredges.create') }}">Create New Customer Edge</a>
</div>
{% endblock %}

app/templates/backbone/prefix.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Backbone Admin Tool - Prefix{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Prefix Details - {{ prefix.prefix}} (IPv{{ prefix.version}})</h1>
</div>
<div class="container">
	<h3>General Details</h3>
	<p>Prefix-Type: {{ prefix.PrefixType.name }}</p>
	<p>Site: {{ prefix.Site.name }}</p>
	<p>Community: {{ prefix.Community.name }} </p>
</div>
<div class="container">
	<h3>Contacts</h3>
	<div class="col-md-11">
		<table class="table table-striped">
		<colgroup>
			<col class="col-md-2">
			<col class="col-md-2">
			<col class="col-md-2">
			<col class="col-md-2">
			<col class="col-md-1">
		</colgroup>
		<tr>
			<th>Nickname</th>
			<th>Lastname</th>
			<th>Firstname</th>
			<th>RIPE-Handle</th>
			<th>Actions</th>
		</tr>
		{% for contact in prefix.contacts %}
		<tr>
			<td>{{ contact.nickname }}</td>
		        <td>{{ contact.lastname }}</td>
			<td>{{ contact.firstname }}</td>
			<td>{{ contact.handle }}</td>
			<td><a href="/prefixes" class="btn btn-danger btn-sm active">Delete</a></td>
		</tr>
		{% endfor %}
		</table>
	</div>
</div>
<div class="container">	
	<h3> Prefix Name Servers</h3>
	<div class="col-md-8">
		<table class="table table-striped">
        	<colgroup>
	            <col class="col-md-8">
		    <col class="col-md-1">
		</colgroup>
		<tr>
			<th>FQDN</th>
			<th>Actions</th>
		</tr>
		{% for ns in prefix.nameservers %}
		<tr>
	        	<td> {{ ns.fqdn }} </td>
			<td><a href="/prefixes" class="btn btn-danger btn-sm active">Delete</a></td>
		</tr>
		{% endfor %}
		<table>
	</div>
	<div class="form-group">
		<label for="sel1">Select list:</label>
		<select class="form-control" id="nameservers">
			{% for ns in nameservers %}
			<option id="{{ ns.id }}">{{ ns.fqdn }}</option>
			{% endfor %}
		</select>
		<a href="/prefixes" class="btn btn-success btn-sm active">Add Nameserver</a>
	</div>
</div>
{% endblock %}

app/templates/backbone/prefixes.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Backbone Admin Tool - Prefixes{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Assigned Prefixes</h1>
</div>
<div class="col-md-15">
	<table class="table table-striped">
        <colgroup>
            <col class="col-md-1">
	    <col class="col-md-1">
	    <col class="col-md-2">
	    <col class="col-md-1">
	    <col class="col-md-2">
	    <col class="col-md-3">
	    <col class="col-md-5">
	</colgroup>
	<tr>
		<th>Prefix</th>
		<th>IP-Version</th>
		<th>Type</th>
		<th>Site</th>
		<th>NameServers</th>
		<th>Contacts</th>
		<th>Actions</th>
	</tr>
	{% for prefix in prefixes %}
	<tr>
        	<td> {{ prefix.prefix }} </td>
	        <td> {{ prefix.version }} </td>
		<td> {{ prefix.PrefixType.name }} </td>
		<td> {{ prefix.Site.name }} </td>
		<td>
			<ul>	
			{% for ns in prefix.nameservers %} 
			<li>{{ ns.fqdn }}</a> </li>
			{% endfor %}
			</ul>
		</td>
		<td>
		        <ul>
                        {% for contact in prefix.contacts %}
                        <li><a href="{{ url_for('contacts.edit', contact_id=contact.id) }}">{{ contact.lastname }}, {{ contact.firstname }} [{{ contact.handle }}]</a> </li>
                        {% endfor %}
                        </ul>
                </td>	
		<td><a class="btn btn-primary btn-sm active" href="{{ url_for('prefixes.edit', prefix_id=prefix.id) }}">Edit</a>&nbsp;<a href="/prefixes" class="btn btn-danger btn-sm active">Delete</a></td>
	</tr>
	{% endfor %}
	<table>
</div>
{% endblock %}