app/blueprints/communities.py
from flask import Blueprint
from flask import render_template, flash, redirect, url_for, request, g  # noqa
from flask.ext.login import current_user, login_required
from datetime import datetime
from app.forms import *
from app.models import *

communities = Blueprint('communities', __name__, template_folder='templates')

@communities.route('/community')
@communities.route('/community/')
@login_required
def list():
    communities_self = Community.query.join(
        Contact,
        Community.contacts
    ).options(db.joinedload('asns')).options(
        db.lazyload('nameservers')
    ).filter_by(id=current_user.id).options(
        db.joinedload('contacts')).all()
    return render_template('community/list.html',
                           communities=communities_self)


@communities.route('/community/<community_id>', methods=['GET', 'POST'])
@login_required
def edit(community_id):
    this_community=Community.query.filter_by(id=community_id).first()
    form = FormCommunity(obj=this_community)
    form.submit.label.text='Update Community'
    if form.validate_on_submit():
        form.populate_obj(this_community)
        db.session.add(this_community)
        this_community.created = datetime.now()
        db.session.commit()
        return redirect(url_for('communities.list'))
    return render_template('community/detail.html',
                           form=form, edit=True)


@communities.route('/community/new', methods=['GET', 'POST'])
@login_required
def create():
    this_community=Community()
    form = FormCommunity()
    form.submit.label.text='Create Community'
    if form.validate_on_submit():
        form.populate_obj(this_community)
        db.session.add(this_community)
        this_community.contacts.append(current_user)
        db.session.commit()
        return redirect(url_for('communities.list'))
    return render_template('community/detail.html',
                           form=form, edit=False)

app/blueprints/contacts.py
from flask import Blueprint
from flask import render_template, flash, redirect, url_for, request, g  # noqa
from flask.ext.login import current_user, login_required
from app.forms import *
from app.models import *

contacts = Blueprint('contacts', __name__, template_folder='templates')


@contacts.route('/contact')
@contacts.route('/contact/')
@login_required
def list():
    return render_template('contact/list.html',
                           contacts=current_user.get_contacts(),
                           admin=current_user.admin)

@contacts.route('/contacts/delete/<contact_id>')
@login_required
def delete(contact_id):
    contact=Contact.query.filter_by(id=contact_id)
    contact.delete()
    db.session.commit()
    flash('Contact deleted successfully!')
    return redirect(url_for('contacts.list'))

@contacts.route('/contact/new', methods=['GET', 'POST'])
@login_required
def create():
    form = FormContact()
    form.communities.query = current_user.get_communities()
    if form.validate_on_submit():
        contact = Contact()
        form.populate_obj(contact)
        contact.set_password(form.newpassword.data)
        db.session.add(contact)
        db.session.commit()
        flash('Contact has been created')
        return redirect(url_for('contacts.list'))
    return render_template("contact/detail.html", form=form)


@contacts.route('/contact/<contact_id>', methods=['GET', 'POST'])
@login_required
def edit(contact_id):
    contact = Contact.query.filter_by(id=contact_id).first_or_404()
    communities_self = Community.query.join(
        Contact,
        Community.contacts
    ).filter_by(id=current_user.id)
    communities_edit = Community.query.join(
        Contact,
        Community.contacts
    ).filter_by(id=contact_id)
    same = False
    for community_self in communities_self:
        for community_edit in communities_edit:
            if community_edit.id == community_self.id:
                community_self.selected = True
                same = True
    if (current_user.admin is False and int(contact_id) != current_user.id) or (
                    current_user.admin is True and same is False):  # noqa
        flash('You don''t have permissions to edit selected contact information')  # noqa
        return redirect(url_for('index'))
    form = FormContact(obj=contact, edit=True)
    form.communities.query = current_user.get_communities()
    if form.validate_on_submit():
        form.populate_obj(contact)
        if form.newpassword is not None:
            contact.set_password(form.newpassword.data)
        db.session.add(contact)
        db.session.commit()
        return redirect(url_for('contacts.list'))
    return render_template('contact/detail.html',
                           contact=contact,
                           communities=communities_self,
                           form=form)

app/blueprints/session.py
from flask import Blueprint

from flask import flash, redirect, session, url_for, request, g  # noqa
from flask.ext.login import login_user, logout_user, current_user, login_required  # noqa
from app.forms import *
from app.models import *
from app.email import *

session = Blueprint('session', __name__, template_folder='templates')



@session.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = Contact.query.filter_by(login=form.email.data).first()
        if user is not None and user.verify_password(form.password.data):
            login_user(user, form.remember_me.data)
            return redirect(request.args.get('next') or url_for('index'))
        flash('Invalid username or password.')
    return render_template('auth/login.html', form=form)


@session.route('/user/<login>')
@login_required
def user(login):
    user = Contact.query.filter_by(login=login).first_or_404()
    page = request.args.get('page', 1, type=int)
    return render_template('base.html')


@session.route('/change-password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        if current_user.verify_password(form.old_password.data):
            current_user.set_password(form.password.data)
            db.session.add(current_user)
            db.session.commit()
            flash('Your password has been updated.')
            return redirect(url_for('index'))
        else:
            flash('Invalid password.')
    return render_template("auth/change_password.html", form=form)


@session.route('/reset', methods=['GET', 'POST'])
def password_reset_request():
    if not current_user.is_anonymous():
        return redirect(url_for('index'))
    form = PasswordResetRequestForm()
    if form.validate_on_submit():
        user = Contact.query.filter_by(mail=form.email.data).first()
        if user:
            token = user.generate_reset_token()
            send_email(user.mail, 'Reset Your Password',
                       'auth/email/reset_password',
                       user=user, token=token,
                       next=request.args.get('next'))
        flash('An email with instructions to reset your password has been '
              'sent to you.')
        return redirect(url_for('login'))
    return render_template('auth/reset_password.html', form=form)


@session.route('/reset/<token>', methods=['GET', 'POST'])
def password_reset(token):
    if not current_user.is_anonymous():
        return redirect(url_for('index'))
    form = PasswordResetForm()
    if form.validate_on_submit():
        user = Contact.query.filter_by(mail=form.email.data).first_or_404()
        if user is None:
            return redirect(url_for('index'))
        if user.reset_password(token, form.password.data):
            flash('Your password has been updated.')
            return redirect(url_for('login'))
        else:
            return redirect(url_for('index'))
    return render_template('auth/reset_password.html', form=form)


@session.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('index'))

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Backbone Admin Tool{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('index') }}">Backbone Admin Tool</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('index') }}">Home</a></li>
                {% if current_user.is_authenticated %}
		<li><a href="{{ url_for('communities.list') }}">Communities</a></li>
		<li><a href="{{ url_for('contacts.list') }}">Contacts</a></li>
        <li><a href="{{ url_for('nameservers.list') }}">NameServers</a></li>
        <li><a href="{{ url_for('asns.list') }}">ASNs</a></li>
		<li><a href="{{ url_for('customeredges.list') }}">CustomerEdges</a></li>
		<li><a href="{{ url_for('prefixes.list') }}">Prefixes</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="/static/img/avatar.jpg">
                        Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
			<li><a href="{{ url_for('contacts.edit', contact_id=current_user.id)}}">Profile</a></li>
                        <li><a href="{{ url_for('session.change_password') }}">Change Password</a></li>
                        <li><a href="{{ url_for('session.logout') }}">Log Out</a></li>
                    </ul>
                </li>
                {% else %}
                <li><a href="{{ url_for('session.login') }}">Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{% endblock %}

app/templates/communities.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Backbone Admin Tool - Contact{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Your Communities</h1>
</div>
<script>
$(document).ready(function(){
		    $('[data-toggle="tooltip"]').tooltip(); 
		    });
</script>
<ul class="nav nav-tabs">
	{% for community in communities %}
	{% if community.isfirst %}
	<li class="active"><a data-toggle="tab" href="#{{ community.id }}">{{ community.name }}</a></li>
        {% else %}
        <li><a data-toggle="tab" href="#{{ community.id }}">{{ community.name }}</a></li>
        {% endif %}
	{% endfor %}
	{% if count == 0 %}
	<li class="active"><a data-toggle="tab" href="#add">Add</a></li>
	{% else %}
	<li><a data-toggle="tab" href="#add">Add</a></li>
	{% endif %}
</ul>

<div class="tab-content">
	{% for community in communities %}
	{% if community.isfirst %}
	<div id="{{ community.id }}" class="tab-pane fade in active">
	{% else %}
	<div id="{{ community.id }}" class="tab-pane fade in">
	{% endif %}
		<h3>{{ community.name }}</h3>
		<div class="container">
			<div class="form-group">
				<label for="usr">Name:</label>
				<input type="text" class="form-control" id="usr" value="{{ community.name }}">
			</div>
			<div class="form-group">
                	        <label for="usr">Shortname:</label>
                        	<input type="text" class="form-control" id="usr" value="{{ community.short }}">
	                </div>
			<div class="form-group">
                	        <label for="usr">Created:</label>
                        	<input type="text" class="form-control" id="usr" value="{{ community.created }}" disabled>
	                </div>
		</div>
		<div class="container">
			<h3>Communities ASNs</h3>
			<p>Following ASNs are operated by your community:</p>            
			<table class="table table-striped">
				<thead>
					<tr>
						<th>ASN</th>
						<th>Name</th>
						<th>Description</th>
						<th>Approved</th>
						<th>Actions</th>
						</tr>
				</thead>
				<tbody>
					{% for asn in community.asns %}
					<tr>
						<td>{{ asn.asn }}</td>
						<td>{{ asn.name }}</td>
						<td>{{ asn.descr }}</td>
						{% if asn.isapproved() %}
						<td><span class="glyphicon glyphicon-ok-circle"></span></td>
						{% else %}
						<td><span class="glyphicon glyphicon-ban-circle"></span></td>
						{% endif %}
						<td>&nbsp;</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
                <div class="container">
                        <h3>Communities Nameservers</h3>
                        <p>Following Nameservers are operated by your community:</p>
                        <table class="table table-striped">
                                <thead>
                                        <tr>
                                                <th>FQDN</th>
						<th>Actions</th>
                                        </tr>
                                </thead>
                                <tbody>
                                        {% for ns in community.nameservers %}
                                        <tr>
                                                <td>{{ ns.fqdn }}</td>
						<td>&nbsp;</td>
                                        </tr>
                                        {% endfor %}
                                </tbody>
                        </table>
                </div>
	</div>
	{% endfor %}
	{% if count == 0 %}
	<div id="add" class="tab-pane fade in active">
	{% else %}
	<div id="add" class="tab-pane fade in">
	{% endif %}
		<h3>Add Community</h3>
		<p>Some content in menu 2.</p>
	</div>
</div>
</br></br></br></br>
		<div class="form-group"> 
			<div class="col-sm-offset-2 col-sm-10">
				<button type="submit" class="btn btn-success">Submit</button>
				<button type="button" class="btn btn-danger">Back</button>
			</div>
		</div>
	</form>	
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
    {% block title %}{{ title }} - FF Backbone{% endblock %} </head>
{% block page_content %}
<div class="page-header">
<div class="col-md-18">
        {% if current_user.is_authenticated %}
            <div class="page-header">
            <h1>Hello, {{ contact.firstname }}!</h1>
            </div>
            <div class="col-md-18">
                We are pleased to meet you again.<br>
                What's going on in your Communities?
            </div>
        {% else %}
            <div class="page-header">
                <h1>Welcome to Backbone Admin Tool</h1><br>
            </div>
            <div class="col-md-18">
                <h3>AS201701 - Current Traffic Status over all</h3>
                <td><img width="1150" src="http://ffrl.de/total.png"></td>
            </div><br>
            <div class="col-md-18">
                <h3>AS201701 - Current Traffic Status per Site</h3>
                <table class="table table-striped">
                    <colgroup>
                        <col class="col-md-2">
	                    <col class="col-md-2">
	                    <col class="col-md-2">
	                </colgroup>
                    <tr>
                        <th>Standort Berlin</th>
                        <th>Standort D&uuml;sseldorf</th>
                        <th>Standort Frankfurt</th>
                    </tr>
	                <tr>
                        <td><img width="350" src="http://ffrl.de/ber.png"></td>
                        <td><img width="350" src="http://ffrl.de/dus.png"></td>
                        <td><img width="350" src="http://ffrl.de/fra.png"></td>
                    </tr>
                    <tr>
                    </tr>
                </table>
            </div>
        {% endif %}
</div></div>
{% endblock %}